### ISSUE TITLE
Can it remove snow/rainfall in lidar data?

### ISSUE THREAD

**Issue by rajeshjoshi8792** [rheinzler/PointCloudDeNoising#10]

**Comment by rheinzler** [comment]
As demonstrated in the evaluation section and the video, it can also remove rainfall. So the answer is yes for rainfall. 
Actually we have never tested the approach with point-clouds corrupted by snow. I assume that the approach is also capable of de-noising snow, as both - rain and snowfall - looks similarly in a LiDAR point-cloud.
