### ISSUE TITLE
Dataset splits

### ISSUE THREAD

**Issue by ptoews** [rheinzler/PointCloudDeNoising#12]
Hi,

I'm trying to replicate experiment 2 from the paper where about 31k road samples were used. First of all, the uploaded dataset contains only 27462 road samples, so I assume the remaining ~4k are taken from the LiLaNet dataset. 

Since that one isn't public, is it possible to publish the chosen selection so that I can take that from the full dataset if I get access to it or to request the subset from the LiLaNet authors? 

Furthermore, the uploaded dataset contains only road samples in training directories. Which samples were used for evaluation?

Lastly, where do the ~103k samples in experiment 3 come from? Is it based on the ~34k clear frames where each was augmented with both fog an rain? If yes, where do the additional ~3k frames compared to experiment 2 come from?

Thanks in advance!

**Comment by rheinzler** [comment]
Hi, unfortunately, we could not publish the road data from the LiLanet paper for legal reasons. Therefore, the published data do not contain road data but the measurements from the climate chamber. However, we have published numerous other road data within the research project. Therefore, I think using the road data from [(SeeingThroughFog)](https://arxiv.org/abs/1902.08913) is a good idea.

**Comment by ptoews** [comment]
Okay, that's understandable. But the dataset seems to contain road data in the directories `train_road_01` and `train_road_02`. Is that only the training part then? And just validation and test splits are not publishable?
