### ISSUE TITLE
dataset labels

### ISSUE THREAD

**Issue by wcshen** [rheinzler/PointCloudDeNoising#13]
hi,
I have downloaded the `train_road_02`,but the labels are all `0`....
is it noraml...

**Comment by rheinzler** [comment]
Yes that's correct. As described in the paper, the road data is not manually annotated and therefore only used for training. Further the augmentation is applied on the road data to obtain rain and fog in road scenarios with ground truth information.

**Comment by russellyq** [comment]
> Yes that's correct. As described in the paper, the road data is not manually annotated and therefore only used for training. Further the augmentation is applied on the road data to obtain rain and fog in road scenarios with ground truth information.

Hi,

So for all road data "train_road_01" and "train_road_02", we have to implement the data augmentation described in your paper ?
