### ISSUE TITLE
Sensor Data Question

### ISSUE THREAD

**Issue by Youngsplace0913** [rheinzler/PointCloudDeNoising#14]
First of all, thank you for sharing a great dataset.

I have a question.
The size of x,y,z of the sensor is 32x400, and can we think of 32 as the number of ring channels of LiDAR?
Then, I don't know how the 400 came out, can you tell me?

In addition, why is the intensity value of labeled points zero?

I'll wait for your answer.
Thank you.

**Comment by Youngsplace0913** [comment]
There is one more question.
In the rain data, most of the label is 100, and there is no 101 rain label. Is this normal?

And except for fog data, 'meteorologicalVisibility_m' and 'rainfallRate_mmh' come out as 'NaN.

I would appreciate it if you could answer after checking.


![image](https://user-images.githubusercontent.com/78135656/122707454-058cb680-d295-11eb-8037-81ebf7a3d564.png)

**Comment by rheinzler** [comment]
> First of all, thank you for sharing a great dataset.
> 
> I have a question.
> The size of x,y,z of the sensor is 32x400, and can we think of 32 as the number of ring channels of LiDAR?
> Then, I don't know how the 400 came out, can you tell me?
> 
> In addition, why is the intensity value of labeled points zero?
> 
> I'll wait for your answer.
> Thank you.

-> there are 400 horizontal columns (forward facing) in the data set. The data set does not contain the complete 360 degree view (1800 columns), as the relevant data is only in the front of the sensor.

-> the intensity Value is taken from the sensor and scaled between 0 and 1.

**Comment by rheinzler** [comment]
> There is one more question.
> In the rain data, most of the label is 100, and there is no 101 rain label. Is this normal?
> 
> And except for fog data, 'meteorologicalVisibility_m' and 'rainfallRate_mmh' come out as 'NaN.
> 
> I would appreciate it if you could answer after checking.
> 
> ![image](https://user-images.githubusercontent.com/78135656/122707454-058cb680-d295-11eb-8037-81ebf7a3d564.png)

-> The labeling is stated in the ReadMe. There is either rain or fog. A combination of both is not present in dat aset (makes no sense in my opinion, but maybe I 'm wrong).

-> the rainfall rate is stable for each rain recording and therefore not always present in the hdf5 attributes. You can use the value from the data set name / folder

**Comment by rheinzler** [comment]
Please reopen the issue, if there is any question left.
