### ISSUE TITLE
Question on data

### ISSUE THREAD

**Issue by russellyq** [rheinzler/PointCloudDeNoising#16]
Hi Thanks for your great work !

I recently downloaded your dataset but I came across some detailed problem when trying to re-implement your work

How to project your point cloud data to the image plane so there is no calibration file ?

Thanks
Best Regards

**Comment by rheinzler** [comment]
The dataset is already in the image plane with a dimension of 32x400.

**Comment by russellyq** [comment]
Got this, thank you. 
So we just need to directly implement the CNN on the raw data in the dataset and there is no need to do any pre-processing on data ?
