### ISSUE TITLE
There is some doubt about the final output of the network

### ISSUE THREAD

**Issue by Yueziyu** [rheinzler/PointCloudDeNoising#18]
First of all, thank you for this excellent job. I have some questions about the final output of the network, is the final output a 32*400 matrix, the same as the labels read from the dataset, and the elements are also 0 and 100,101.102? Or is it a label manipulation or is it a matrix with the number of channels representing categories like Lilanet? Thank you。

**Comment by rheinzler** [comment]
The output of the resulting network is a 32*400 matrix with 3 channels representing the three classes (clear, rain, fog).
Actually I started the label range at 100 to get some margin to the conventional object detection labels (car, pedestrian, cyclist, ...) which often starts at 0 or 1.
