### ISSUE TITLE
Release of the data!

### ISSUE THREAD

**Issue by shuangjiexu** [rheinzler/PointCloudDeNoising#2]
Hi, Thanks for your amazing work!
The Adverse Weather has been a troubling question in the 3D field. Experiments from your paper give reasonable results for these scenes, which made me eager to try this task. Would you please release the dataset, or give us a schedule of planned releases?
Any help would be greatly appreciated!

**Comment by tornadomeet** [comment]
Also looking forward.

**Comment by rheinzler** [comment]
Thank you very much for your messages. We plan to publish the data set at the beginning of the 2nd quarter 2020.

**Comment by rheinzler** [comment]
The dataset is available :-)
