### ISSUE TITLE
The meaning of four classes

### ISSUE THREAD

**Issue by shuangjiexu** [rheinzler/PointCloudDeNoising#3]
Thanks for your open-source dataset!

I found that there are four classes in label: `[0, 100, 101, 102]`, what's there meaning respective?

Any help is appreciated.

**Comment by rheinzler** [comment]
The meaning of the labels are provided in the readme file:
"We used the following label mapping for a single lidar point: 
0: no label, 100: valid/clear, 101: rain, 102: fog"
