### ISSUE TITLE
Seems like the dataset is not available?

### ISSUE THREAD

**Issue by giorking** [rheinzler/PointCloudDeNoising#4]
Hi all, 
    I am wondering if there is any friend has download the dataset recently? I followed the tutorial to register in DENSE dataset webpage and get the download link via the email. However, seems like the file in the link has been removed. Please help me to find the correct method for getting the dataset:) Thanks.

**Comment by giorking** [comment]
@rheinzler Hi rheinzler, if you don't mind, could you please help me to figure it out or give me some hints? Thanks.

**Comment by rheinzler** [comment]
Hi @giorking. Your mentioned method is correct. I registered myself a couple of days ago and I downloaded the dataset last Sunday. There was no problem. Can you access the download page and the directories of the cloud store?

**Comment by giorking** [comment]
@rheinzler Thanks for you response. Yes. I got a link of CloudStore after registration but it showed 'File not found' in the CloudStore webpage. If you don't mind, I can share the link of CloudStore I got with you. Thanks.

**Comment by rheinzler** [comment]
I just registered myself again. Unfortunately I get the same result ('file not found'). The cloud storage is provided by the University of Ulm, I contact the IT department there for a solution. Sorry for the inconvenience and thanks for informing me.

**Comment by giorking** [comment]
@rheinzler No problem. Thanks for you help and hopefully we can get the dataset back very soon:)

**Comment by giorking** [comment]
@rheinzler The problem is solved. Thanks:)

**Comment by rheinzler** [comment]
@giorking thank you very much for the information and for closing the issue. Sorry for the late reply, that the data set is back again, I was busy preparing the video for the ICRA conference.
