### ISSUE TITLE
Dataset file pairs: Strongest or last?

### ISSUE THREAD

**Issue by ptoews** [rheinzler/PointCloudDeNoising#8]
I noticed that some of the files in the dataset have the same name, except one has a suffix `_2`, as an example:
`LidarImage_000000001.hdf5` and `LidarImage_000000001_2.hdf5`.
What does that mean? Are those two files describing the same point in time but one contains the strongest and the other the last returns of the lidar? If yes, which is which?

Also, why do these pairs exist only for a part of the dataset and not all measurements?

Thanks in advance!

**Comment by rheinzler** [comment]
The dataset contains only one return. However, for the clear sections both returns are available.

**Comment by ptoews** [comment]
Do you know which return the single point clouds contain? Single or last?

Also, I compared the secondary point clouds with their corresponding partner and apparently all pairs are identical. Is that correct?

**Comment by rheinzler** [comment]
The data contains the strongest return.
Thanks for the hint. I just checked the code, indeed there is a bug in the exporter script for the clear data.
