### ISSUE TITLE
Label semantics

### ISSUE THREAD

**Issue by ptoews** [rheinzler/PointCloudDeNoising#9]
I'm trying to understand what the different label categories in the dataset mean. First of all, what is difference between `FogA`, `FogB` and `FogC`? I had a look at the count of fog points per category but that didn't help.

The distributions of the rain categories are even more confusing to me. I noticed that already in the paper in figure 5:
![image](https://user-images.githubusercontent.com/1062119/105917790-2d078c00-6033-11eb-97c1-02ec5d9f447c.png)
Why does a rain rate of 15mm/h cause the highest count of rain points in comparison, and 33mm/h only so few?

**Comment by rheinzler** [comment]
Hello @ptoews, 

Q#1: A B and C are recordings of the same scene and consecutive repetitions. We started at 5m visibility and waited until the fog is dissipated to 100m visibility. We have repeated these recordings several times and numbered them with A, B and C.

Q#2: That's correct. The rain at 15mm/h corresponds more to a light drizzle. This might affect the utilized lidar more strongly than a normal rain. At least that's what the data shows.
